name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install Node dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Install Jekyll dependencies
      run: |
        gem install bundler
        bundle install || gem install jekyll
    
    - name: Build Jekyll site
      run: bundle exec jekyll build || jekyll build
      env:
        JEKYLL_ENV: production
    
    - name: Serve Jekyll site in background
      run: |
        bundle exec jekyll serve --detach || jekyll serve --detach &
        sleep 10
        curl -I http://localhost:4000 || echo "Server starting..."
    
    - name: Run Playwright tests
      run: npm test
      env:
        CI: true
        BASE_URL: http://localhost:4000
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
